apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: splitting
  namespace: chaos-testing
spec:
  service: dummy
  backends:
  - service: grpc-client
    weight: 900m
  - service: error-injector
    weight: 100m